# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelifcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotrabalhomodel',
            name='max_disciplina',
            field=models.IntegerField(default=1, verbose_name=b'Quantidade m\xc3\xa1xima de autores por trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracaotrabalhomodel',
            name='min_disciplina',
            field=models.IntegerField(default=1, verbose_name=b'Quantidade minima de  autores  por trabalho '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='facebook',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='git',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='site',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalhomodel',
            name='resumo',
            field=models.CharField(max_length=1000),
        ),
    ]
